[package]
name = "kernel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stivale = { git = "https://github.com/Andy-Python-Programmer/stivale" }

[build-dependencies]
nasm-rs = "0.2.0"
