[package]
name = "kernel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stivale-boot = "0.2.1"

[build-dependencies]
nasm-rs = "0.2.0"
